security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_BETAREADER
        ROLE_BETAREADER:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                # Redirect to previous page after login
                use_referer: true
            # oauth:
            #     resource_owners:
            #         facebook:           "/login/check-facebook"
            #         google:             "/login/check-google"
            #     login_path:        /login
            #     failure_path:      /login

            #     oauth_user_provider:
            #         #this is my custom user provider, created from FOSUBUserProvider - will manage the
            #         #automatic user registration on your site, with data from the provider (facebook. google, etc.)
            #         service: my_user_provider
            logout:       true
            anonymous:    true

            #Remember me functionality
            remember_me:
                secret: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/custom/, role: ROLE_ADMIN }
        - { path: ^/wiki/, role: ROLE_BETAREADER }
